// Control Plane <-> Worker protocol (docs/architecture/04-api-design.md
// §10, docs/architecture/17-workers.md §1). Deliberately simplified from
// the doc's "one long-lived bidirectional stream" into two RPCs (a
// server-stream the Worker keeps open to receive work, plus a unary
// call to report back) - still real gRPC, still one persistent
// connection per Worker, just not literally bidirectional-in-one-stream.
// Flagged here explicitly as the walking skeleton's own simplification,
// not a silent deviation from the documented design.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: internal/execution/adapters/grpc/proto/worker.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WorkerService_Register_FullMethodName        = "/worker.WorkerService/Register"
	WorkerService_StreamJobs_FullMethodName      = "/worker.WorkerService/StreamJobs"
	WorkerService_ReportJobStatus_FullMethodName = "/worker.WorkerService/ReportJobStatus"
)

// WorkerServiceClient is the client API for WorkerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WorkerServiceClient interface {
	// Register is called once at Worker startup, advertising
	// supported_engines/labels (docs/architecture/17-workers.md §7's
	// Worker registration - the Run Dispatcher's claim query matches
	// against exactly this).
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	// StreamJobs is the long-lived connection - the Worker keeps this
	// call open for its entire lifetime; the Control Plane pushes a
	// JobAssignment down it every time the Run Dispatcher matches a
	// queued Run to this Worker.
	StreamJobs(ctx context.Context, in *StreamJobsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[JobAssignment], error)
	// ReportJobStatus is how progress/completion flows back - a plain
	// unary call per status update, not a second stream.
	ReportJobStatus(ctx context.Context, in *JobStatusReport, opts ...grpc.CallOption) (*Ack, error)
}

type workerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkerServiceClient(cc grpc.ClientConnInterface) WorkerServiceClient {
	return &workerServiceClient{cc}
}

func (c *workerServiceClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, WorkerService_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) StreamJobs(ctx context.Context, in *StreamJobsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[JobAssignment], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WorkerService_ServiceDesc.Streams[0], WorkerService_StreamJobs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamJobsRequest, JobAssignment]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkerService_StreamJobsClient = grpc.ServerStreamingClient[JobAssignment]

func (c *workerServiceClient) ReportJobStatus(ctx context.Context, in *JobStatusReport, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, WorkerService_ReportJobStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkerServiceServer is the server API for WorkerService service.
// All implementations must embed UnimplementedWorkerServiceServer
// for forward compatibility.
type WorkerServiceServer interface {
	// Register is called once at Worker startup, advertising
	// supported_engines/labels (docs/architecture/17-workers.md §7's
	// Worker registration - the Run Dispatcher's claim query matches
	// against exactly this).
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	// StreamJobs is the long-lived connection - the Worker keeps this
	// call open for its entire lifetime; the Control Plane pushes a
	// JobAssignment down it every time the Run Dispatcher matches a
	// queued Run to this Worker.
	StreamJobs(*StreamJobsRequest, grpc.ServerStreamingServer[JobAssignment]) error
	// ReportJobStatus is how progress/completion flows back - a plain
	// unary call per status update, not a second stream.
	ReportJobStatus(context.Context, *JobStatusReport) (*Ack, error)
	mustEmbedUnimplementedWorkerServiceServer()
}

// UnimplementedWorkerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWorkerServiceServer struct{}

func (UnimplementedWorkerServiceServer) Register(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedWorkerServiceServer) StreamJobs(*StreamJobsRequest, grpc.ServerStreamingServer[JobAssignment]) error {
	return status.Error(codes.Unimplemented, "method StreamJobs not implemented")
}
func (UnimplementedWorkerServiceServer) ReportJobStatus(context.Context, *JobStatusReport) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportJobStatus not implemented")
}
func (UnimplementedWorkerServiceServer) mustEmbedUnimplementedWorkerServiceServer() {}
func (UnimplementedWorkerServiceServer) testEmbeddedByValue()                       {}

// UnsafeWorkerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkerServiceServer will
// result in compilation errors.
type UnsafeWorkerServiceServer interface {
	mustEmbedUnimplementedWorkerServiceServer()
}

func RegisterWorkerServiceServer(s grpc.ServiceRegistrar, srv WorkerServiceServer) {
	// If the following call panics, it indicates UnimplementedWorkerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WorkerService_ServiceDesc, srv)
}

func _WorkerService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_StreamJobs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamJobsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WorkerServiceServer).StreamJobs(m, &grpc.GenericServerStream[StreamJobsRequest, JobAssignment]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkerService_StreamJobsServer = grpc.ServerStreamingServer[JobAssignment]

func _WorkerService_ReportJobStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JobStatusReport)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).ReportJobStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_ReportJobStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).ReportJobStatus(ctx, req.(*JobStatusReport))
	}
	return interceptor(ctx, in, info, handler)
}

// WorkerService_ServiceDesc is the grpc.ServiceDesc for WorkerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorkerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "worker.WorkerService",
	HandlerType: (*WorkerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _WorkerService_Register_Handler,
		},
		{
			MethodName: "ReportJobStatus",
			Handler:    _WorkerService_ReportJobStatus_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamJobs",
			Handler:       _WorkerService_StreamJobs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "internal/execution/adapters/grpc/proto/worker.proto",
}
