// Control Plane <-> Worker protocol (docs/architecture/04-api-design.md
// §10, docs/architecture/17-workers.md §1). Deliberately simplified from
// the doc's "one long-lived bidirectional stream" into two RPCs (a
// server-stream the Worker keeps open to receive work, plus a unary
// call to report back) - still real gRPC, still one persistent
// connection per Worker, just not literally bidirectional-in-one-stream.
// Flagged here explicitly as the walking skeleton's own simplification,
// not a silent deviation from the documented design.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: internal/execution/adapters/grpc/proto/worker.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	WorkerId         string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	SupportedEngines []string               `protobuf:"bytes,2,rep,name=supported_engines,json=supportedEngines,proto3" json:"supported_engines,omitempty"`
	Labels           map[string]string      `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_internal_execution_adapters_grpc_proto_worker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_execution_adapters_grpc_proto_worker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_internal_execution_adapters_grpc_proto_worker_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *RegisterRequest) GetSupportedEngines() []string {
	if x != nil {
		return x.SupportedEngines
	}
	return nil
}

func (x *RegisterRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_internal_execution_adapters_grpc_proto_worker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_execution_adapters_grpc_proto_worker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_internal_execution_adapters_grpc_proto_worker_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

type StreamJobsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamJobsRequest) Reset() {
	*x = StreamJobsRequest{}
	mi := &file_internal_execution_adapters_grpc_proto_worker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamJobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamJobsRequest) ProtoMessage() {}

func (x *StreamJobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_execution_adapters_grpc_proto_worker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamJobsRequest.ProtoReflect.Descriptor instead.
func (*StreamJobsRequest) Descriptor() ([]byte, []int) {
	return file_internal_execution_adapters_grpc_proto_worker_proto_rawDescGZIP(), []int{2}
}

func (x *StreamJobsRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

type JobAssignment struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RunId           string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	OrganizationId  string                 `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	WorkspaceId     string                 `protobuf:"bytes,3,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	ExecutionEngine string                 `protobuf:"bytes,4,opt,name=execution_engine,json=executionEngine,proto3" json:"execution_engine,omitempty"`
	// config_bundle is real content this slice sources from the Variables
	// context's own cascade resolution (a `file_template` variable), not
	// a fabricated bypass - the GitOps context that would normally supply
	// this (a real repo checkout) doesn't exist in this codebase yet,
	// documented as a real, later integration point.
	ConfigBundle  string `protobuf:"bytes,5,opt,name=config_bundle,json=configBundle,proto3" json:"config_bundle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobAssignment) Reset() {
	*x = JobAssignment{}
	mi := &file_internal_execution_adapters_grpc_proto_worker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobAssignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobAssignment) ProtoMessage() {}

func (x *JobAssignment) ProtoReflect() protoreflect.Message {
	mi := &file_internal_execution_adapters_grpc_proto_worker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobAssignment.ProtoReflect.Descriptor instead.
func (*JobAssignment) Descriptor() ([]byte, []int) {
	return file_internal_execution_adapters_grpc_proto_worker_proto_rawDescGZIP(), []int{3}
}

func (x *JobAssignment) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *JobAssignment) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *JobAssignment) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *JobAssignment) GetExecutionEngine() string {
	if x != nil {
		return x.ExecutionEngine
	}
	return ""
}

func (x *JobAssignment) GetConfigBundle() string {
	if x != nil {
		return x.ConfigBundle
	}
	return ""
}

type JobStatusReport struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	RunId string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	// organization_id/workspace_id are echoed back from the JobAssignment
	// that triggered this report - needed because RLS-scoped lookups
	// (docs/architecture/05-database.md §1) require organization_id
	// up front, not discoverable from run_id alone without an unscoped
	// (root-privileged) query this codebase's runtime deliberately never
	// uses (internal/platform/config's own DatabaseURL/AppDatabaseURL
	// split).
	OrganizationId string `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	WorkspaceId    string `protobuf:"bytes,3,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	// status is one of the Run domain's own RunStatus values this Worker
	// is honest about actually producing: "applying", "applied", "failed",
	// "errored" - never "planning"/"planned"/"policy_check"/
	// "awaiting_approval", which need pieces (Policy, Approval) this
	// codebase hasn't built yet.
	Status        string `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	LogLine       string `protobuf:"bytes,5,opt,name=log_line,json=logLine,proto3" json:"log_line,omitempty"`
	ErrorMessage  string `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobStatusReport) Reset() {
	*x = JobStatusReport{}
	mi := &file_internal_execution_adapters_grpc_proto_worker_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobStatusReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobStatusReport) ProtoMessage() {}

func (x *JobStatusReport) ProtoReflect() protoreflect.Message {
	mi := &file_internal_execution_adapters_grpc_proto_worker_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobStatusReport.ProtoReflect.Descriptor instead.
func (*JobStatusReport) Descriptor() ([]byte, []int) {
	return file_internal_execution_adapters_grpc_proto_worker_proto_rawDescGZIP(), []int{4}
}

func (x *JobStatusReport) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *JobStatusReport) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *JobStatusReport) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *JobStatusReport) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *JobStatusReport) GetLogLine() string {
	if x != nil {
		return x.LogLine
	}
	return ""
}

func (x *JobStatusReport) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_internal_execution_adapters_grpc_proto_worker_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_internal_execution_adapters_grpc_proto_worker_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_internal_execution_adapters_grpc_proto_worker_proto_rawDescGZIP(), []int{5}
}

func (x *Ack) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_internal_execution_adapters_grpc_proto_worker_proto protoreflect.FileDescriptor

const file_internal_execution_adapters_grpc_proto_worker_proto_rawDesc = "" +
	"\n" +
	"3internal/execution/adapters/grpc/proto/worker.proto\x12\x06worker\"\xd3\x01\n" +
	"\x0fRegisterRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12+\n" +
	"\x11supported_engines\x18\x02 \x03(\tR\x10supportedEngines\x12;\n" +
	"\x06labels\x18\x03 \x03(\v2#.worker.RegisterRequest.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\".\n" +
	"\x10RegisterResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\"0\n" +
	"\x11StreamJobsRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\"\xc2\x01\n" +
	"\rJobAssignment\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId\x12!\n" +
	"\fworkspace_id\x18\x03 \x01(\tR\vworkspaceId\x12)\n" +
	"\x10execution_engine\x18\x04 \x01(\tR\x0fexecutionEngine\x12#\n" +
	"\rconfig_bundle\x18\x05 \x01(\tR\fconfigBundle\"\xcc\x01\n" +
	"\x0fJobStatusReport\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId\x12!\n" +
	"\fworkspace_id\x18\x03 \x01(\tR\vworkspaceId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x19\n" +
	"\blog_line\x18\x05 \x01(\tR\alogLine\x12#\n" +
	"\rerror_message\x18\x06 \x01(\tR\ferrorMessage\"\x15\n" +
	"\x03Ack\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok2\xc9\x01\n" +
	"\rWorkerService\x12=\n" +
	"\bRegister\x12\x17.worker.RegisterRequest\x1a\x18.worker.RegisterResponse\x12@\n" +
	"\n" +
	"StreamJobs\x12\x19.worker.StreamJobsRequest\x1a\x15.worker.JobAssignment0\x01\x127\n" +
	"\x0fReportJobStatus\x12\x17.worker.JobStatusReport\x1a\v.worker.AckB=Z;platform-of-platform/internal/execution/adapters/grpc/protob\x06proto3"

var (
	file_internal_execution_adapters_grpc_proto_worker_proto_rawDescOnce sync.Once
	file_internal_execution_adapters_grpc_proto_worker_proto_rawDescData []byte
)

func file_internal_execution_adapters_grpc_proto_worker_proto_rawDescGZIP() []byte {
	file_internal_execution_adapters_grpc_proto_worker_proto_rawDescOnce.Do(func() {
		file_internal_execution_adapters_grpc_proto_worker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_execution_adapters_grpc_proto_worker_proto_rawDesc), len(file_internal_execution_adapters_grpc_proto_worker_proto_rawDesc)))
	})
	return file_internal_execution_adapters_grpc_proto_worker_proto_rawDescData
}

var file_internal_execution_adapters_grpc_proto_worker_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_internal_execution_adapters_grpc_proto_worker_proto_goTypes = []any{
	(*RegisterRequest)(nil),   // 0: worker.RegisterRequest
	(*RegisterResponse)(nil),  // 1: worker.RegisterResponse
	(*StreamJobsRequest)(nil), // 2: worker.StreamJobsRequest
	(*JobAssignment)(nil),     // 3: worker.JobAssignment
	(*JobStatusReport)(nil),   // 4: worker.JobStatusReport
	(*Ack)(nil),               // 5: worker.Ack
	nil,                       // 6: worker.RegisterRequest.LabelsEntry
}
var file_internal_execution_adapters_grpc_proto_worker_proto_depIdxs = []int32{
	6, // 0: worker.RegisterRequest.labels:type_name -> worker.RegisterRequest.LabelsEntry
	0, // 1: worker.WorkerService.Register:input_type -> worker.RegisterRequest
	2, // 2: worker.WorkerService.StreamJobs:input_type -> worker.StreamJobsRequest
	4, // 3: worker.WorkerService.ReportJobStatus:input_type -> worker.JobStatusReport
	1, // 4: worker.WorkerService.Register:output_type -> worker.RegisterResponse
	3, // 5: worker.WorkerService.StreamJobs:output_type -> worker.JobAssignment
	5, // 6: worker.WorkerService.ReportJobStatus:output_type -> worker.Ack
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_execution_adapters_grpc_proto_worker_proto_init() }
func file_internal_execution_adapters_grpc_proto_worker_proto_init() {
	if File_internal_execution_adapters_grpc_proto_worker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_execution_adapters_grpc_proto_worker_proto_rawDesc), len(file_internal_execution_adapters_grpc_proto_worker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_execution_adapters_grpc_proto_worker_proto_goTypes,
		DependencyIndexes: file_internal_execution_adapters_grpc_proto_worker_proto_depIdxs,
		MessageInfos:      file_internal_execution_adapters_grpc_proto_worker_proto_msgTypes,
	}.Build()
	File_internal_execution_adapters_grpc_proto_worker_proto = out.File
	file_internal_execution_adapters_grpc_proto_worker_proto_goTypes = nil
	file_internal_execution_adapters_grpc_proto_worker_proto_depIdxs = nil
}
